name: Build and publish Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_pub:
    runs-on: ubuntu-latest

    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      REPO: ${{ secrets.DOCKER_REPO }}


    steps:
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$REPO:${GITHUB_SHA} -f Dockerfile .
      - name: Push image to docker.io
        run: docker push $LOGIN/$REPO:${GITHUB_SHA}
